# Generated by Django 4.2.1 on 2023-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
