# Generated by Django 4.2.1 on 2023-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0002_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
