# Generated by Django 4.2.1 on 2023-05-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0004_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_of_movie', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(5, 'ROMANCE'), (4, 'DRAMA'), (1, 'HORROR'), (3, 'SCI-FI'), (2, 'COMEDY'), (0, 'INNE')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_web.movieadditionalinfo'),
        ),
    ]
