# Generated by Django 4.2.1 on 2023-05-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0005_movieadditionalinfo_movie_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieadditionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HORROR'), (0, 'INNE'), (4, 'DRAMA'), (3, 'SCI-FI'), (5, 'ROMANCE'), (2, 'COMEDY')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_description', models.TextField(blank=True, default='')),
                ('mark', models.PositiveSmallIntegerField(default=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_web.movie')),
            ],
        ),
    ]
